- src/redux/modules/userSlice.js
> Fix : userSlice 수정

- src/components/Header.js
- src/pages/Post/PostDetail.jsx
- src/redux/modules/mypageSlice.js
- src/redux/modules/userSlice.js
수정 페이지 이동 에러, 헤더의 프로필 사진 로딩 수정
> Fix: 수정 페이지 이동 에러, 헤더의 프로필 사진 로딩 수정

- src/components/Footer.js
- src/components/UI/StSelector.js
- src/pages/User/Login.jsx
- src/pages/User/SignUp.jsx
- src/pages/User/State.jsx
- src/styles/GlobalStyle.js
Style: 로그인, 회원가입, 헤더, 풋터 CSS 수정
> Style: 로그인, 회원가입, 헤더, 풋터 CSS 수정 

- src/pages/Chat/ MyChat.jsx
- src/pages/Chat/Chat.jsx
> Hotfix: 채팅 작동 수정

- src/pages/Chat/Chat.jsx
> Fix: 문의하기 채팅 수정

- src/pages/Chat/Chat.jsx
> Fix: 채팅 수정

- src/components/Card.js
- src/pages/Post/PostDetail.jsx
> Fix: 카드에서 state 넘겨주기->상세페이지 api 사용

- src/pages/Home/CardList.js
- src/pages/Post/PostList.jsx
- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/pages/Post/element/LocalFalse/HelpUsFalse.jsx
- src/pages/Post/element/LocalFalse/HelpeeFalse.jsx
- src/pages/Post/element/LocalFalse/HelperFalse.jsx
- src/pages/Post/element/LocalTrue/AllTrue.jsx
- src/pages/Post/element/LocalTrue/HelpUsTrue.jsx
- src/pages/Post/element/LocalTrue/HelpeeTrue.jsx
- src/pages/Post/element/LocalTrue/HelperTrue.jsx
- src/redux/modules/postSlice.js
> Feat: 게시글 없을시 알림글 출력 기능

- package-lock.json
- package.json
- src/App.css
- src/api/axios.js
- src/components/Header.js
- src/components/UI/CardStyle.js/StCommon.js
- src/components/UI/CardStyle.js/StElements.js
- src/pages/Home/CardList.js
- src/pages/Home/Home.js
- src/pages/Home/Style/StHome.js
- src/pages/Post/PostCreate.jsx
- src/pages/Post/PostDetail.jsx
- src/pages/Post/PostUpdate.jsx
- src/pages/Post/StPostDetail.js
- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/redux/modules/postSlice.js
> Update:  develop -> feature/test 

- src/components/Card.js
- src/redux/modules/userSlice.js
- src/redux/store/store.js
userSlice의 전역상태(로그인한 유저의 정보) 값만 저장 하도록 설정
> Fix: persist store whitelist 추가

- src/api/axios.js
- src/pages/Home/Home.js
- src/pages/Mypage/Mypage.jsx
- src/pages/User/Login.jsx
- src/redux/modules/userSlice.js
엑세스 토큰 만료 시 재발급, 리프레쉬 토큰 만료 시 로그인 유도 코드 추가
> Feat: 토큰 만료 시 재발급 기능 추가

- src/components/Card.js
- src/components/UI/CardStyle/StCommon.js
- src/pages/Post/PostList.jsx
- src/pages/Post/PostUpdate.jsx
- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/pages/Post/element/LocalFalse/HelpUsFalse.jsx
- src/pages/Post/element/LocalFalse/HelpeeFalse.jsx
- src/pages/Post/element/LocalFalse/HelperFalse.jsx
- src/redux/modules/postSlice.js
>  Style:조회 페이지 토글 버튼

- src/components/Carousel.js
- src/pages/Post/PostCreate.jsx
> Feat: 게시글 생성 케러셀 추가

- src/pages/Post/PostUpdate.jsx
- src/pages/Post/element/Calender.jsx
- src/redux/store/store.js
수정 페이지 새로고침 시 정상화
수정 폼 가로 크기 조정
헬퍼스 설명 문구 수정
> Fix: 수정 페이지 새로고침 시 정상화

- src/api/axios.js
- src/components/UI/CardStyle/StElements.js
- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/redux/modules/postSlice.js
> Fix:전체 게시물 에러 해결

- src/api/axios.js
- src/components/Carousel.js
- src/components/UI/CardStyle/StElements.js
- src/pages/Post/PostCreate.jsx
- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/redux/modules/postSlice.js
Reverts Project-Helpus/Helpus#50
> Revert "전체 게시물 에러 해결"

- src/api/axios.js
- src/components/UI/CardStyle/StElements.js
- src/pages/Post/PostList.jsx
- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/redux/modules/postSlice.js
> Fix:검색 기능 에러 해결

- src/pages/Mypage/Mypage.jsx
- src/pages/Post/PostCreate.jsx
- src/pages/Post/element/LocalFalse/AllFalse.jsx
마이페이지 게시물 불러오기, 게시물 생성 후 화면 이동
> Fix: 마이페이지 게시물 불러오기, 게시물 생성 후 화면 이동

- src/pages/Post/PostCreate.jsx
- src/redux/modules/chatSlice.js
- src/redux/modules/mypageSlice.js
- src/redux/modules/postSlice.js
- src/redux/modules/userSlice.js
게시물 생성 후 성공시 화면 이동, thunk funcion name 수정
> Fix: 게시물 생성 후 성공시 화면 이동

- src/pages/Post/PostDetail.jsx
> Fix:찜하기 코드 수정

- src/pages/Home/Home.js
- src/pages/Post/PostList.jsx
- src/redux/modules/userSlice.js
> Fix: 카카오 로그인 예외처리 정상화

- src/components/Header.js
> Fix: kakaoLogin 변수명 변경

- src/pages/Mypage/MypageDetail.jsx
- src/pages/Post/PostList.jsx
> Fix: isLoginKakao 변수명 변경

- public/index.html
- src/pages/Post/PostList.jsx
> Fix: 카카오맵 mixted content 스크립트 추가

- src/pages/User/State.jsx
> Fix: 가져오는 주소 키값 변경

- src/api/axios.js
- src/pages/Post/PostDetail.jsx
- src/redux/modules/postSlice.js
> Fix: 마감 api 수정

- src/components/Header.js
- src/pages/Home/Home.js
- src/pages/Home/Style/StHome.js
> Style: 메인페이지 디자인 수정

- src/components/Card.js
- src/pages/Post/PostCreate.jsx
> Fix: 게시물 생성 예외처리

- src/pages/Post/PostDetail.jsx
> Feat:카카오 유효성 검사 추가

- src/pages/Post/PostDetail.jsx
- src/pages/Post/PostUpdate.jsx
- src/redux/modules/postSlice.js
> Fix: 게시물 수정 에러 수정

- src/pages/Post/PostDetail.jsx
> Fix: 게시물 상세 시간 표시 수정

- public/index.html
> Fix: google analytics 수정

- src/pages/Post/PostList.jsx
> Feat:페이지 이동후 tabButton 변화

- src/components/Header.js
- src/pages/Post/PostList.jsx
- src/redux/modules/postSlice.js
> Feat:검색후 게시글 조회 페이지 이동

- src/components/DropdownMenu.js
- src/components/Header.js
- src/pages/Home/Home.js
> Feat:검색 기록 초기화

- src/pages/Chat/ MyChat.jsx
- src/pages/Chat/OpenChat.jsx
- src/pages/Post/PostDetail.jsx
- src/redux/api/axios.js
- src/redux/modules/chatSlice.js
화면 전환 수정, 약속 Flow 카드 보이는 부분 수정
> Fix: 취소하기 -> 카드 사라짐

- src/pages/Post/PostCreate.jsx
- src/pages/Post/PostUpdate.jsx
- src/redux/api/axios.js
- src/redux/modules/chatSlice.js
- src/redux/modules/postSlice.js
로그인 인증 메세지 변경,  게시물 생성, 수정 후 화면 이동 처리 정상화, _getState 요청 실패시 return 수정
> Fix: 로그인 인증 메세지 변경

- src/pages/Post/PostDetail.jsx
- src/pages/Post/StPostDetail.js
> Feat: 찜한 상태 상세 페이지에 적용

- src/redux/api/axios.js
> Fix: 로그인 만료 메세지 , -> . 변경

- src/pages/Mypage/Mypage.jsx
- src/pages/Mypage/MypagePostsDetail.jsx
- src/pages/Mypage/MypageWishList.jsx
- src/pages/Mypage/element/Rating.js
> Feat: 마이페이지 별점 추가

- src/pages/User/Login.jsx
> Fix: 로그인 시  메인페이지로 이동

- src/pages/Post/PostCreate.jsx
> Fix: 헬피,헬퍼,헬퍼스 설명 문구 수정

- src/pages/Mypage/MypageDetail.jsx
> Fix: 프로필 수정 이메일 input 스타일 변경

- src/components/DropdownNotification.js
- src/components/Header.js
- src/pages/Chat/ MyChat.jsx
- src/redux/api/axios.js
- src/redux/modules/chatSlice.js
> Fix: 알림 읽음 기능 정상화

- src/components/DropdownNotification.js
- src/components/Header.js
- src/pages/Chat/ MyChat.jsx
- src/pages/Home/Home.js
- src/pages/Home/Style/StHome.js
- src/pages/Mypage/MypageDetail.jsx
- src/redux/api/axios.js
- src/redux/modules/chatSlice.js
알림 읽음 기능 정상화, 홈 화면 Style 수정, 설명 문구 수정
> Fix: 알림 읽음 기능 정상화 

- src/pages/Chat/ MyChat.jsx
- src/pages/Chat/OpenChat.jsx
- src/pages/Chat/element/AppointmentCard.jsx
- src/pages/Chat/element/ChatInput.jsx
- src/pages/Chat/element/ChatList.jsx
- src/pages/Chat/element/RatingCard.jsx
- src/pages/Chat/styles/StChat.js
- src/utils/chatting.js
> Refactor: 컴포넌트 분리, Util Fucntion 분리

- src/pages/Chat/element/RatingCard.jsx
> Fix: 평점 하트 안내문 추가

- src/pages/Chat/OpenChat.jsx
> Fix: 수락하기 버그 수정

- src/pages/Chat/OpenChat.jsx
> Fix: 취소하기 send_image 남는 버그 수정

- src/components/Carousel.js
- src/components/UI/CardStyle/Row.js
- src/components/UI/CardStyle/StCommon.js
> Style: 카드 눌리는 현상 수정

- src/components/DropdownMenu.js
- src/components/DropdownNotification.js
- src/hooks/useDropDetectClose.js
- src/redux/modules/chatSlice.js
custom hook rename,
잘못된 alert 창 삭제
> Rename: custom hook rename

- src/components/UI/CardStyle/StElements.js
- src/pages/Mypage/Style/StMypage.js
- src/pages/User/KakaoLogin.jsx
- src/pages/User/State.jsx
> Fix: 카카오 로그인 시 화면 이동 메인으로 수정

- src/pages/Post/PostCreate.jsx
- src/pages/Post/element/styles/StPostDetail.js
- src/redux/modules/postSlice.js
게시물 생성 후 해당 상세 페이지로 이동,
태그 스타일 변경,
마감, 수정, 삭제 버튼 크기 수정
> Fix: 게시물 생성 후 해당 상세 페이지로 이동

- src/pages/Post/PostCreate.jsx
- src/redux/api/axios.js
> Fix: q -> page 수정

- src/redux/modules/postSlice.js
> Fix: 조회페이지 새로고침시 전체 게시물 보이게 처리

- src/pages/Post/element/LocalFalse/AllFalse.jsx
- src/pages/Post/element/styles/Spinner.js
- src/redux/modules/postSlice.js
> Feat: 게시물 로딩시 spinner 추가

- README.md
Trouble shotting document link 삽입
> Docs: README.md update
